config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
	get "signin" => 'devise/sessions#new'
	delete "signout" => 'devise/sessions#destroy'
	get 'signup' => 'devise/registrations#new'
  end
 root 'pages#home'
 get 'about' => 'pages#about'
 get 'contact' => 'pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter

	def authorized?(action, subject =nil)
		user && user.admin?
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
		 :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def access_denied(exception)
  	redirect_to root_path, alert: exception.message
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<!-- Navigation Bar -->
<nav class="navbar navbar-toggleable-md navbar-light bg-faded ">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav mr-auto">
        <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Contact me", contact_path, class: "nav-link" %></li>
      </ul>
      <ul class="nav navbar-nav"
        <!-- Login Buttons -->
        <% if user_signed_in? %>
          <li class="nav-item pull-md-right"><%= link_to "Log out", signout_path, method: :delete, class: "nav-link btn btn-info btn-sm" %></li>  
        <% else %>
          <li class="nav-item pull-md-right"><%= link_to "Sign in", signin_path, class: "nav-link btn btn-secondary" %></li> 
          <li class="nav-item pull-md-right"><%= link_to "Sign up", signup_path, class: "nav-link btn btn-primary text-white"%></li>
        <% end %>
      </ul>
    </div>
</nav>

<!-- Flash Messages -->
  <% flash.each do |name,message| %>
    <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>
    
    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 One Month</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron jumbotron-home">
    <div class="container">
        <h1>About One Month Rails</h1>
        <p>Where I learned to hate Windows and wish I had a mac... <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>    
</div>
<div class="container">
        <div class="row">
            <div class="col-md-4">
                <h4>LEARN PROJECT MANAGEMENT</h4>
        <blockquote class="blockquote">
  				<p class="mb-0">You’ll learn how to get projects done on time, on spec, and under budget, how to conquer scope creep, and manage risk. Oh, and also a thing or two about cakes.</p>
  				<footer class="blockquote-footer">‎Product Manager at 18F <cite title="Source Title">Alex Bisker</cite></footer>
		</blockquote>
            </div>
            <div class="col-md-4">
                <h5>BUILD YOUR MINIMUM VIABLE PRODUCT</h5>
        <blockquote class="blockquote">
  				<p class="mb-0">You never truly know whether you’re delivering the right product to right person at the right time. This course is designed to help solve that problem.</p>
  				<footer class="blockquote-footer">‎Tech Entrepreneur & Instructor <cite title="Source Title">Evan Kimbrell</cite></footer>
		</blockquote>
            </div>
            <div class="col-md-4">
                <h4>RUBY DEVELOPER IN 30 DAYS</h4>
        <blockquote class="blockquote">
  				<p class="mb-0">In just one month, I'll teach you how to code in the most flexible programming language in the world.</p>
  				<footer class="blockquote-footer">‎Instructor & CEO of One Month<cite title="Source Title">Mattan Griffel</cite></footer>
		</blockquote>
            </div>

app/views/pages/contact.html.erb
<div class="jumbotron jumbotron-home">
    <div class="container">
        <h1>Contact Info</h1>
        <p>I am going to write some random info here... <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>    
</div>
<div class="container">
<dl class="row">
  <dt class="col-sm-3">Name</dt>
  <dd class="col-sm-9">Brent Bolinger</dd>

  <dt class="col-sm-3">City</dt>
  <dd class="col-sm-9">A name that is in every state, "Springfield".</dd>

  <dt class="col-sm-3">My Job</dt>
  <dd class="col-sm-9">Chief Engineer at a Fox Affiliate.</dd>
    </dl>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
 <div class="jumbotron jumbotron-home">
    <div class="container">
        <h1 class="display-4">Welcome Back!</h1>
    </div>
</div>
<%else%>
     <div class="jumbotron jumbotron-home">
        <div class="container">
            <h1 class="display-4">Welcome to my website!</h1>
            <p class= "lead">I made this following a tutorial. I may have cursed more then once during this project but I at least made it this far.</p>
            <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %> 
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
            </div>
        </div>
</div>
<% end %>